---

- name: Install /etc/sudoers.tmp file.
  action: template src=../files/sudoers dest=/etc/sudoers.tmp

- name: Set the permissions.
  file: path=/etc/sudoers.tmp owner=root group=root mode=0440

- name: Final sudoers file check
  shell: visudo -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers

- name: Restart ssh.
  command: ssh restart